<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Rice2k.FolderVault</AssemblyName>
    <RootNamespace>Rice2k.FolderVault</RootNamespace>
    <Version>0.2.3</Version>
    <AssemblyVersion>0.2.3.0</AssemblyVersion>
    <FileVersion>0.2.3.0</FileVersion>
    <InformationalVersion>0.2.3-alpha</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="DokanNet" Version="2.3.0.3" />
  </ItemGroup>

</Project>
